services:
  ros2_dev:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: kuka_ros2_container
    network_mode: "host" 
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ..:/home/rosuser/kuka_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true